language: c

install:
    - sudo apt-get install valgrind
    - make all
    - sudo make install
    - |
        sudo sed -i -re 's/^(hosts: .*$)/\1 docker/' /etc/nsswitch.conf

script:
    - valgrind --leak-check=full --error-exitcode=2 --suppressions=valgrind.supp ./test
